package i18nx

const I18nTemplate = `// Code generated by tools. DO NOT EDIT!
package {{ .Package }}

import (
	"github.com/shrewx/ginx/pkg/i18nx"
	"github.com/nicksnyder/go-i18n/v2/i18n"
)

func init() {
	i18nx.RegisterHooks(RegisterI18nMessages)
}

func (v {{ .ClassName }}) Localize(manager *i18nx.Localize, lang string) i18nx.I18nMessage {
	return i18nx.NewMessage(v.Key(), v.Prefix()).Localize(manager, lang)
}

func (v {{ .ClassName }}) Key() string {
	return string(v)
}

func (v {{ .ClassName }}) Prefix() string {
	return "{{ .Prefix }}"
}

func (v {{ .ClassName }}) ID() string {
	if v.Prefix() == "" {
		return v.Key()
	}
	return v.Prefix() + "." + v.Key()
}

func (v {{ .ClassName }}) Value() string {
	return i18nx.NewMessage(v.Key(), v.Prefix()).Value()
}

func (v {{ .ClassName }}) Message(lang string) string {
	return v.Localize(i18nx.Instance(), lang).Value()
}

{{range $lang, $error := .Messages}}func Get{{ $.ClassName }}{{upper $lang}}Messages() []*i18n.Message {
	var fields []*i18n.Message
{{range $error}}
	fields = append(fields, &i18n.Message{ID: {{.T}}.ID(), Other: "{{.Message}}"}){{end}}
	return fields
}

{{end}}func RegisterI18nMessages() { {{range $lang, $error := .Messages}}
	i18nx.AddMessages("{{$lang}}", Get{{ $.ClassName }}{{upper $lang}}Messages()) {{end}} 
}
`
