package i18nx

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestI18nTemplate_Content(t *testing.T) {
	// Test that the template contains expected content
	assert.Contains(t, I18nTemplate, "Code generated by tools. DO NOT EDIT!")
	assert.Contains(t, I18nTemplate, "package {{ .Package }}")
	assert.Contains(t, I18nTemplate, "github.com/shrewx/ginx/pkg/i18nx")
	assert.Contains(t, I18nTemplate, "github.com/nicksnyder/go-i18n/v2/i18n")
	assert.Contains(t, I18nTemplate, "func init()")
	assert.Contains(t, I18nTemplate, "i18nx.RegisterHooks(RegisterI18nMessages)")
}

func TestI18nTemplate_Methods(t *testing.T) {
	// Test that the template contains all expected methods
	expectedMethods := []string{
		"Localize",
		"Key",
		"Prefix",
		"ID",
		"Value",
		"Message",
	}

	for _, method := range expectedMethods {
		assert.Contains(t, I18nTemplate, "func (v {{ .ClassName }}) "+method)
	}
}

func TestI18nTemplate_KeyFunction(t *testing.T) {
	// Test that the Key function template is correct
	assert.Contains(t, I18nTemplate, "func (v {{ .ClassName }}) Key() string {")
	assert.Contains(t, I18nTemplate, "return string(v)")
}

func TestI18nTemplate_PrefixFunction(t *testing.T) {
	// Test that the Prefix function template is correct
	assert.Contains(t, I18nTemplate, "func (v {{ .ClassName }}) Prefix() string {")
	assert.Contains(t, I18nTemplate, "return \"{{ .Prefix }}\"")
}

func TestI18nTemplate_IDFunction(t *testing.T) {
	// Test that the ID function template is correct
	assert.Contains(t, I18nTemplate, "func (v {{ .ClassName }}) ID() string {")
	assert.Contains(t, I18nTemplate, "if v.Prefix() == \"\" {")
	assert.Contains(t, I18nTemplate, "return v.Key()")
	assert.Contains(t, I18nTemplate, "return v.Prefix() + \".\" + v.Key()")
}

func TestI18nTemplate_ValueFunction(t *testing.T) {
	// Test that the Value function template is correct
	assert.Contains(t, I18nTemplate, "func (v {{ .ClassName }}) Value() string {")
	assert.Contains(t, I18nTemplate, "return i18nx.NewMessage(v.Key(), v.Prefix()).Value()")
}

func TestI18nTemplate_MessageFunction(t *testing.T) {
	// Test that the Message function template is correct
	assert.Contains(t, I18nTemplate, "func (v {{ .ClassName }}) Message(lang string) string {")
	assert.Contains(t, I18nTemplate, "return v.Localize(i18nx.Instance(), lang).Value()")
}

func TestI18nTemplate_MapFunction(t *testing.T) {
	// Test that the map generation function is present
	assert.Contains(t, I18nTemplate, "func Get{{ .ClassName }}Map() map[string]map[{{ .ClassName }}]string")
	assert.Contains(t, I18nTemplate, "return map[string]map[{{ .ClassName }}]string{")
	assert.Contains(t, I18nTemplate, "{{range $lang, $error := .Messages}}")
	assert.Contains(t, I18nTemplate, "\"{{$lang}}\": {")
	assert.Contains(t, I18nTemplate, "{{range $error}}{{.T}}: \"{{.Message}}\",")
}

func TestI18nTemplate_RegisterFunction(t *testing.T) {
	// Test that the register function is present
	assert.Contains(t, I18nTemplate, "func RegisterI18nMessages() {")
	assert.Contains(t, I18nTemplate, "messageMap := Get{{ .ClassName }}Map()")
	assert.Contains(t, I18nTemplate, "for lang, messages := range messageMap {")
	assert.Contains(t, I18nTemplate, "var i18nMessages []*i18n.Message")
	assert.Contains(t, I18nTemplate, "for key, message := range messages {")
	assert.Contains(t, I18nTemplate, "i18nMessages = append(i18nMessages, &i18n.Message{ID: key.ID(), Other: message})")
	assert.Contains(t, I18nTemplate, "i18nx.AddMessages(lang, i18nMessages)")
}

func TestI18nTemplate_Imports(t *testing.T) {
	// Test that all required imports are present
	expectedImports := []string{
		"github.com/shrewx/ginx/pkg/i18nx",
		"github.com/nicksnyder/go-i18n/v2/i18n",
	}

	for _, imp := range expectedImports {
		assert.Contains(t, I18nTemplate, imp)
	}
}

func TestI18nTemplate_Structure(t *testing.T) {
	// Test that the template has proper structure
	lines := strings.Split(I18nTemplate, "\n")

	// Should have package declaration
	assert.True(t, strings.HasPrefix(lines[0], "// Code generated"))
	assert.True(t, strings.Contains(lines[1], "package {{ .Package }}"))

	// Should have import block
	importStart := -1
	importEnd := -1
	for i, line := range lines {
		if strings.Contains(line, "import (") {
			importStart = i
		}
		if importStart != -1 && strings.Contains(line, ")") && importEnd == -1 {
			importEnd = i
			break
		}
	}
	assert.True(t, importStart != -1, "Import block should be present")
	assert.True(t, importEnd != -1, "Import block should be closed")

	// Should have init function
	hasInit := false
	for _, line := range lines {
		if strings.Contains(line, "func init()") {
			hasInit = true
			break
		}
	}
	assert.True(t, hasInit, "Init function should be present")
}
