// Code generated by tools. DO NOT EDIT!!!!

import (
	"context"

	"github.com/shrewx/ginx"
)

{{range .Operations}}
//{{if .Summary}} {{ .Summary }}{{end}}
type {{ .OperationId }} struct {
{{range .Fields}}{{ . }}
{{end}}
}

// Path 返回请求路径
func (req *{{ .OperationId }}) Path() string {
	return {{ .Path }}
}

// Method 返回请求方法
func (req *{{ .OperationId }}) Method() string {
	return {{ .Method }}
}

{{if .StatusErrors}}
{{range .StatusErrors}}
// {{ . }}
{{end}}
{{end}}

// Invoke 执行请求
func (req *{{ .OperationId }}) Invoke(ctx context.Context, c ginx.Client) (ginx.ResponseBind, error) {
	return c.Invoke(ctx, req)
}

{{if .HasResp}}
// InvokeAndBind 执行请求并绑定响应
func (req *{{ .OperationId }}) InvokeAndBind(ctx context.Context, c ginx.Client, config *ginx.RequestConfig) (*{{ .RespType }}, error) {
	resp := new({{ .RespType }})
	// 将配置注入到 context
	if config != nil {
		ctx = context.WithValue(ctx, ginx.RequestConfigKey{}, config)
	}

	response, err := req.Invoke(ctx, c)
	if err != nil {
		return nil, err
	}
	if err = response.Bind(resp); err != nil {
		return nil, err
	}
	return resp, err
}
{{else}}
// InvokeAndBind 执行请求
func (req *{{ .OperationId }}) InvokeAndBind(ctx context.Context, c ginx.Client, config *ginx.RequestConfig) error {
	// 将配置注入到 context
	if config != nil {
		ctx = context.WithValue(ctx, ginx.RequestConfigKey{}, config)
	}

	_, err := req.Invoke(ctx, c)
	return err
}
{{end}}

{{end}}

