// Code generated by tools. DO NOT EDIT!!!!

{{range .Operations}}
//{{if .Summary}} {{ .Summary }}{{end}}
type {{ .OperationId }} struct {
{{range .Fields}}{{ . }}
{{end}}
}

// Path 返回请求路径
func (req *{{ .OperationId }}) Path() string {
	return {{ .Path }}
}

// Method 返回请求方法
func (req *{{ .OperationId }}) Method() string {
	return {{ .Method }}
}

{{if .StatusErrors}}
{{range .StatusErrors}}
// {{ . }}
{{end}}
{{end}}

{{end}}

