// Code generated by tools. DO NOT EDIT!!!!

import (
	"net/http"
	"time"

	"github.com/shrewx/ginx"
)

// ClientOption 用于配置客户端的选项
type ClientOption func(*{{ .ClientInstanceName }})

// WithInterceptors 批量添加拦截器
func WithInterceptors(interceptors ...ginx.Interceptor) ClientOption {
	return func(c *{{ .ClientInstanceName }}) {
		c.interceptors = append(c.interceptors, interceptors...)
	}
}

// WithDefaultHeaders 批量设置默认 Headers
func WithDefaultHeaders(headers map[string]string) ClientOption {
	return func(c *{{ .ClientInstanceName }}) {
		for k, v := range headers {
			c.defaultReqConfig.Headers[k] = v
		}
	}
}

// WithDefaultCookies 批量设置默认 Cookies
func WithDefaultCookies(cookies ...*http.Cookie) ClientOption {
	return func(c *{{ .ClientInstanceName }}) {
		c.defaultReqConfig.Cookies = append(c.defaultReqConfig.Cookies, cookies...)
	}
}

// WithDefaultTimeout 设置默认超时时间
func WithDefaultTimeout(timeout time.Duration) ClientOption {
	return func(c *{{ .ClientInstanceName }}) {
		c.defaultReqConfig.Timeout = &timeout
	}
}

// WithSyncInvoker 注册同步调用器
func WithSyncInvoker(invoker ginx.SyncInvoker) ClientOption {
	return func(c *{{ .ClientInstanceName }}) {
		c.syncInvoker = invoker
	}
}

// WithAsyncInvoker 注册异步调用器
func WithAsyncInvoker(invoker ginx.AsyncInvoker) ClientOption {
	return func(c *{{ .ClientInstanceName }}) {
		c.asyncInvoker = invoker
	}
}

// WithDefaultInvokeMode 设置默认调用模式
func WithDefaultInvokeMode(mode ginx.InvokeMode) ClientOption {
	return func(c *{{ .ClientInstanceName }}) {
		c.defaultMode = mode
	}
}

