// Code generated by tools. DO NOT EDIT!!!!

import (
	"context"
	"net/http"

	"github.com/shrewx/ginx"
)

// {{ .ClientInterfaceName }} 客户端接口
type {{ .ClientInterfaceName }} interface {
{{range .Operations}}//{{if .Summary}} {{ .Summary }}{{end}}
	{{ .OperationId }}(ctx context.Context, {{if .HasReq}}req *{{ .ReqType }}, {{end}}opts ...ginx.RequestOption){{if .HasResp}} (*{{ .RespType }}, error){{else}} error{{end}}
	{{end}}
}

// {{ .ClientInstanceName }} 客户端实现
type {{ .ClientInstanceName }} struct {
	client          ginx.Client
	ctx             context.Context
	config          *ginx.RequestConfig
	syncInvoker     ginx.SyncInvoker
	asyncInvoker    ginx.AsyncInvoker
	defaultMode     ginx.InvokeMode
}

// New{{ .ClientInterfaceName }} 创建新的客户端实例
func New{{ .ClientInterfaceName }}(schema, host string, port uint16, opts ...ClientOption) *{{ .ClientInstanceName }} {
	client := &{{ .ClientInstanceName }}{
		client: ginx.Client{},
		config: &ginx.RequestConfig{
			Schema:  schema,
			Host:    host,
			Port:    port,
			Headers: make(map[string]string),
			Cookies: make([]*http.Cookie, 0),
		},
	}

	// 应用客户端选项
	for _, opt := range opts {
		opt(client)
	}

	return client
}

{{range .Operations}}
//{{if .Summary}} {{ .Summary }}{{end}}
func (c *{{ $.ClientInstanceName }}) {{ .OperationId }}(ctx context.Context, {{if .HasReq}}req *{{ .ReqType }}, {{end}}opts ...ginx.RequestOption) {{if .HasResp}}(*{{ .RespType }}, error){{else}}error{{end}} {
{{if not .HasReq}}
	req := &{{ .ReqType }}{}
{{end}}
{{if .HasResp}}
	resp := new({{ .RespType }})
	if err := ginx.Invoke(ctx, req, resp, c.config, c.getSyncInvoker(), c.asyncInvoker, opts...); err != nil {
		return nil, err
	}
	return resp, nil
{{else}}
	return ginx.Invoke(ctx, req, nil, c.config, c.getSyncInvoker(), c.asyncInvoker, opts...)
{{end}}
}
{{end}}

// getSyncInvoker 获取同步调用器
func (c *{{ .ClientInstanceName }}) getSyncInvoker() ginx.SyncInvoker {
	if c.syncInvoker != nil {
		return c.syncInvoker
	}

	return &c.client
}