// Code generated by tools. DO NOT EDIT!!!!

import (
	"context"

	"github.com/shrewx/ginx"
)

// {{ .ClientInterfaceName }} 客户端接口
type {{ .ClientInterfaceName }} interface {
{{range .Operations}}//{{if .Summary}} {{ .Summary }}{{end}}
	{{ .OperationId }}(ctx context.Context, {{if .HasReq}}req *{{ .ReqType }}, {{end}}opts ...ginx.RequestOption){{if .HasResp}} (*{{ .RespType }}, error){{else}} error{{end}}
	{{end}}
}

// {{ .ClientInstanceName }} 客户端实现
type {{ .ClientInstanceName }} struct {
	Client          ginx.Client
	ctx             context.Context
	config *ginx.RequestConfig
	syncInvoker     ginx.SyncInvoker
	asyncInvoker    ginx.AsyncInvoker
	defaultMode     ginx.InvokeMode
}

// New{{ .ClientInterfaceName }} 创建新的客户端实例
func New{{ .ClientInterfaceName }}(c ginx.Client, opts ...ClientOption) *{{ .ClientInstanceName }} {
	client := &{{ .ClientInstanceName }}{
		Client:          c,
		config: ginx.NewRequestConfig(),
	}

	// 应用客户端选项
	for _, opt := range opts {
		opt(client)
	}

	return client
}

{{range .Operations}}
//{{if .Summary}} {{ .Summary }}{{end}}
func (c *{{ $.ClientInstanceName }}) {{ .OperationId }}(ctx context.Context, {{if .HasReq}}req *{{ .ReqType }}, {{end}}opts ...ginx.RequestOption) {{if .HasResp}}(*{{ .RespType }}, error){{else}}error{{end}} {
{{if not .HasReq}}
	req := &{{ .ReqType }}{}
{{end}}
{{if .HasResp}}
	resp := new({{ .RespType }})
	if err := ginx.Invoke(&c.Client, ctx, req, resp, c.config, c.asyncInvoker, opts...); err != nil {
		return nil, err
	}
	return resp, nil
{{else}}
	return ginx.Invoke(&c.Client, ctx, req, nil, c.config, c.asyncInvoker, opts...)
{{end}}
}
{{end}}

// getSyncInvoker 获取同步调用器
func (c *{{ .ClientInstanceName }}) getSyncInvoker() ginx.SyncInvoker {
	if c.syncInvoker != nil {
		return c.syncInvoker
	}
	client := &c.Client
	return client
}