// Code generated by tools. DO NOT EDIT!
package errors

import (
	"github.com/shrewx/ginx/pkg/i18nx"
	"github.com/shrewx/ginx/pkg/statuserror"
	"github.com/nicksnyder/go-i18n/v2/i18n"
)

func init() {
	i18nx.RegisterHooks(RegisterErrorMessages)
}

func (v StatusError) WithArgs(args ...interface{}) statuserror.CommonError {
	return statuserror.NewStatusErr(v.Key(), v.Code()).WithArgs(args)
}

func (v StatusError) Localize(manager *i18nx.Localize, lang string) i18nx.I18nMessage {
	return statuserror.NewStatusErr(v.Key(), v.Code()).Localize(manager, lang)
}

func (v StatusError) LocalizeValue(value interface{}) statuserror.CommonError {
	return statuserror.NewStatusErr(v.Key(), v.Code()).WithParams(map[string]interface{}{"Value": value})
}

func (v StatusError) LocalizeData(data map[string]interface{}) statuserror.CommonError {
	return statuserror.NewStatusErr(v.Key(), v.Code()).WithParams(data)
}

func (v StatusError) StatusCode() int {
	return statuserror.NewStatusErr(v.Key(), v.Code()).StatusCode()
}

func (v StatusError) Key() string {
	switch v { 
	case BadRequest:
		return "BadRequest"
	case Unauthorized:
		return "Unauthorized"
	case Forbidden:
		return "Forbidden"
	case NotFound:
		return "NotFound"
	case Conflict:
		return "Conflict"
	case InternalServerError:
		return "InternalServerError"
	}
	return "UNKNOWN"
}

func (v StatusError) Code() int64 {
	return int64(v)
}

func (v StatusError) Error() string {
	return statuserror.NewStatusErr(v.Key(), v.Code()).Error()
}

func (v StatusError) Value() string {
	return statuserror.NewStatusErr(v.Key(), v.Code()).Value()
}

func (v StatusError) WithField(key string, value string) statuserror.CommonError {
	return statuserror.NewStatusErr(v.Key(), v.Code()).WithField(key, value)
}

func GetStatusErrorZHMessages() []*i18n.Message {
	var messages []*i18n.Message

	messages = append(messages, &i18n.Message{ID: BadRequest.Key(), Other: "请求参数错误"})
	messages = append(messages, &i18n.Message{ID: Unauthorized.Key(), Other: "未授权，请先授权"})
	messages = append(messages, &i18n.Message{ID: Forbidden.Key(), Other: "禁止操作"})
	messages = append(messages, &i18n.Message{ID: NotFound.Key(), Other: "资源未找到"})
	messages = append(messages, &i18n.Message{ID: Conflict.Key(), Other: "资源冲突"})
	messages = append(messages, &i18n.Message{ID: InternalServerError.Key(), Other: "内部处理错误"})
	return messages
}

func RegisterErrorMessages() { 
	i18nx.AddMessages("zh", GetStatusErrorZHMessages())  
}
