package statuserror

const StatusErrorTemplate = `// Code generated by tools. DO NOT EDIT!
package {{ .Package }}

import (
	"github.com/shrewx/ginx/pkg/i18nx"
	"github.com/shrewx/ginx/pkg/statuserror"
	"github.com/nicksnyder/go-i18n/v2/i18n"
)

func init() {
	i18nx.RegisterHooks(RegisterErrorMessages)
}

func (v {{ .ClassName }}) WithArgs(args ...interface{}) statuserror.CommonError {
	return statuserror.NewStatusErr(v.Key(), v.Code()).WithArgs(args)
}

func (v {{ .ClassName }}) Localize(manager *i18nx.Localize, lang string) i18nx.I18nMessage {
	return statuserror.NewStatusErr(v.Key(), v.Code()).Localize(manager, lang)
}

func (v {{ .ClassName }}) LocalizeValue(value interface{}) statuserror.CommonError {
	return statuserror.NewStatusErr(v.Key(), v.Code()).WithParams(map[string]interface{}{"Value": value})
}

func (v {{ .ClassName }}) LocalizeData(data map[string]interface{}) statuserror.CommonError {
	return statuserror.NewStatusErr(v.Key(), v.Code()).WithParams(data)
}

func (v {{ .ClassName }}) StatusCode() int {
	return statuserror.NewStatusErr(v.Key(), v.Code()).StatusCode()
}

func (v {{ .ClassName }}) Key() string {
	switch v { {{range .Errors}}
	case {{ .Key}}:
		return "{{ .Key}}"{{end}}
	}
	return "UNKNOWN"
}

func (v {{ .ClassName }}) Code() int64 {
	return int64(v)
}

func (v {{ .ClassName }}) Error() string {
	return statuserror.NewStatusErr(v.Key(), v.Code()).Error()
}

func (v {{ .ClassName }}) Value() string {
	return statuserror.NewStatusErr(v.Key(), v.Code()).Value()
}

func (v {{ .ClassName }}) WithField(key string, value string) statuserror.CommonError {
	return statuserror.NewStatusErr(v.Key(), v.Code()).WithField(key, value)
}

{{range $lang, $error := .Messages}}func Get{{ $.ClassName }}{{upper $lang}}Messages() []*i18n.Message {
	var messages []*i18n.Message
{{range $error}}
	messages = append(messages, &i18n.Message{ID: {{.Key}}.Key(), Other: "{{.Message}}"}){{end}}
	return messages
}

{{end}}func RegisterErrorMessages() { {{range $lang, $error := .Messages}}
	i18nx.AddMessages("{{$lang}}", Get{{ $.ClassName }}{{upper $lang}}Messages()) {{end}} 
}
`
